### ISSUE TITLE
No success event with dataType: "html"

### ISSUE THREAD

**Issue by hirasso** [dtipson/noisy-json#1]
Hi there, looks promising, I would love to use your little plugin! I have a problem though: My "success" event doesn't fire if i use your plugin. The site I am calling is responding with html, not json, maybe the issue is related to that?

``` javascript
            $.ajax({
                url: url,
                type: "get",
                dataType: "njson html",
                success: function (data) {
                    // this only fires if I don't use your plugin.
                    console.log(data);

                }
            })
```

**Comment by dtipson** [comment]
Not sure if it's related, but success is a deprecated way of accessing the results of a Deferred.  I've used this with .done()/.fail()/.always() successfully.  That said, I thought success was a least still around (even if not preferred), so I'll looking into what might be going on.

Also, is the site that's responding _actually_ responding with actual html?  That would never work if that's the case: this approach is designed for same domain json.  The html/txt converters exist only because old IEs have to have funky MIME types set in order to work: but the content being sent is still (and has to be) json.
